

## keyboardType
* number-pad : Specifies a numeric keypad designed for PIN entry.
* decimal-pad : Specifies a keyboard with numbers and a decimal point.
* phone-pad : Specifies a keypad designed for entering telephone numbers
[HERE](https://developer.apple.com/documentation/uikit/uikeyboardtype)

#### Fix a bug when user focus on Text Input field
* [https://facebook.github.io/react-native/docs/keyboardavoidingview.html](KeyboardAvoidingView)
